config/routes.rb
Rails.application.routes.draw do
  resources :cows
  root 'cows#index'
  get 'cows/index'
  get 'cows/new'

  resources :cows do
    member do
      get :upvote
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cow.rb
class Cow < ApplicationRecord
    validates :url, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cows_controller.rb
class CowsController < ApplicationController
  before_action :set_cow, only: [:show, :edit, :update, :destroy]

  def index
    @cows = Cow.all
  end

  def new
    @cow = Cow.new
  end

  def show
    render :show
  end

  def create
    @cow = Cow.new(cow_params)

    if @cow.save
      redirect_to @cow, alert: "Cow created"
    else
      # Preserve validation error message array before render
      flash[:message] = @cow.errors.full_messages
      render new_cow_path, alert: "Error: Your cow could not be created"
    end
  end

  def edit
  end

  def update
    @cow.update(cow_params)
    redirect_to @cow, alert: "Cow updated"
  end

  def set_cow
    @cow = Cow.find(params[:id])
  end

  def upvote
    Cow.increment_counter(:clicks, params[:id])
    redirect_to cow_path, alert: "Cow click recorded"
  end

  def destroy
    @cow.destroy
    redirect_to root_path, alert: "Cow record deleted"
  end

  private

  def cow_params
    params.require(:cow).permit(:url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cows_helper.rb
module CowsHelper
end

app/views/cows/_form.html.erb
<%= form_for @cow do |f| %>

  <div class="field">
    <%= f.label :url, "Photo Url" %>
    <%= f.text_field :url %>
  </div>

  <br>
  
  <%= f.submit %>
<% end %>

app/views/cows/edit.html.erb
<h1>Edit cow</h1>

<h2>ID: <%= @cow.id %></h2>
<a href="<%= cow_path(@cow) %>"><img src="<%= @cow.url %>"></a><br>
<p>Clicks: <%= @cow.clicks %></p>

<%= render 'form' %>

app/views/cows/index.html.erb
<h1>Our Cows</h1>

<% if not @cows %>
  No cows yet
<% else %>
  <% @cows.each do |cow| %>
    <div class="cow">
      <h2>ID: <%= link_to cow.id, cow_path(cow) %></h2>
      <a href="<%= cow_path(cow) %>"><img src="<%= cow.url %>"></a><br>
      <p class="clicks">Clicks: <%= cow.clicks %></p>
    </div>
  <% end %>
<% end %>
<p><%= button_to "Add a cow", new_cow_path, method: "get" %></p>

app/views/cows/new.html.erb
<h1>Create a new cow</h1>
<%= render 'form' %>

app/views/cows/show.html.erb
<h1>One Cow Among Many</h1>

<h2>ID: <%= @cow.id %></h2>
<img src="<%= @cow.url %>"><br>
<p>Clicks: <%= @cow.clicks %></p>

<%= button_to 'Like', upvote_cow_path(@cow.id), method: "get" %>

<br><br>

<%= button_to "Edit", edit_cow_path, method: "get" %>
<%= button_to "Delete", cow_path, method: "delete" %>

app/views/layouts/_alerts.html.erb
<% if not flash.empty? %>
  <div id="error_explanation">
    <ul>
      <% flash.each do |key, value| %>
        <% Array(value).each do |item| %>
          <li><%= item.html_safe %></li>
        <% end %>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CowClicker</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">

      <header>
        <div id="logo"><%= link_to "CowClicker", root_path %></div>
        <div id="tagline">Click a cow, any cow</div>
      </header>

      <div class="main">
        <%= render "layouts/alerts" %>
        <%= yield %>
      </div>

      <footer>
        &copy; 2020 <b>CowClicker</b><br>
        <a href="/terms-and-conditions.html">Privacy</a> | <a href="/privacy.htm">Terms and Conditions</a>
      </footer>

    </div>
  </body>
</html>